printshellcmds: true
notemp: true
keep-going: true
use-apptainer: true
apptainer-args: "--bind $PWD/../../.. --bind /pollard/data/projects/bsmith/strain-corr/include/StrainFacts:/src/StrainFacts"
configfile: "$PWD/config.yaml"
