# # Override default parameters (set in `workflow/config.yaml`) by resetting their values here:
# main_container: 'docker://bsmith89/strainpgc-wf@sha256:a71ae3c3e28b9e95f9bac0a9283452ac216dc8eda0479e222a137650929667e6'
# gtpro_container: 'docker://bsmith89/gtpro@sha256:dedf350917364f7c3018124fdb9840fdbb188700b216a42acf54d194e14b2df3'
# preprocessing_infix: 'dedup.deadapt.qtrim'
# sfacts_infix: 'filt-poly05-cvrg05.ss-g10000-block0-seed0.sfacts-s85-seed0'
# sfacts_strategy_path: 'sfacts_strategy.args'
# pangenome_profiling_agg_level: '75'

# Projects should set their own config for the following parameters:
# (For an examples see `examples/wf_example/config.yaml`.)
# Directory for all workflow output files.
outdir: 'results'
# Directory for benchmarking results.
benchdir: 'benchmark'
# Sample manifest linking sample names to r1/r2 files
sample_manifest_path: 'sample.tsv'
# List of species_ids for MIDAS profiling
species_list_path: 'species.list'
# Mapping from single-copy genes to their species_id
species_gene_path: 'species_gene.tsv'
# Path to illumina_adapters FASTA
illumina_adapters_fasta_path: 'ref/illumina_adapters.fa'
# Directory to use for MIDASDB managed by MIDAS.
midasdb_dir: 'ref/midasdb_uhgg.d'
# Stem of the GT-Pro reference DB
gtpro_ref_name: 'ref/gtpro/20190723_881species'
# Location of the GT-Pro reference DB
gtpro_ref_dir: 'ref/gtpro'
# Which files to make by default (excluding the `outdir` prefix)
target_all_noprefix: ['species/102506/spgc.strain.tsv', 'species/102506/spgc.gene.tsv']
